# TCL File Generated by Component Editor 18.1
# Wed Sep 18 17:12:41 CEST 2024
# MODIFIED


################################################ 
# onewire_master_controller "OneWire Master Controller" v1.0
# Yifeng Wang 2024.09.18.17:12:41
# Host transaction layer issues by process data from/into the onewire master IP.
################################################ 

################################################ 
# request TCL package from ACDS 16.1
################################################ 
package require -exact qsys 16.1


################################################ 
# module onewire_master_controller
################################################ 
set_module_property DESCRIPTION \
"<html>
Host transaction layer issues by process data from/into the onewire master IP. <br>
It wraps around the link layer by automatically perform functional commands on a specific 1-Wire device. <br>
<br>
Usage:

</html>"

set_module_property NAME onewire_master_controller
set_module_property VERSION 24.0.918
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property ICON_PATH ../figures/mu3e_logo.png
set_module_property DISPLAY_NAME "OneWire Master Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK myelaborate


################################################ 
# file sets
################################################ 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL onewire_master_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file onewire_master_controller.vhd VHDL PATH onewire_master_controller.vhd TOP_LEVEL_FILE
add_fileset_file pseudo_clock_down_convertor.vhd VHDL PATH pseudo_clock_down_convertor.vhd


################################################
# parameters
#################################################
add_parameter REF_CLOCK_RATE NATURAL 156250000
set_parameter_property REF_CLOCK_RATE DEFAULT_VALUE 156250000
set_parameter_property REF_CLOCK_RATE DISPLAY_NAME "Reference clock rate"
set_parameter_property REF_CLOCK_RATE TYPE NATURAL
set_parameter_property REF_CLOCK_RATE UNITS Hertz
set_parameter_property REF_CLOCK_RATE ALLOWED_RANGES 1_000_000:10_000_000_000
set_parameter_property REF_CLOCK_RATE HDL_PARAMETER true
set dscpt \
"<html>
Set the reference input clock rate. <br>
This IP has internal clock down-convertor for counting 1 us interval. <br>
The input must be greater <b>(&ge 1 MHz)</b> than the requirement of the timing parameter granularity, which is 1 us. <br>
<b> You only need to set this parameter according to your system bus clock rate. </b> 
</html>"
set_parameter_property REF_CLOCK_RATE LONG_DESCRIPTION $dscpt
set_parameter_property REF_CLOCK_RATE DESCRIPTION $dscpt

add_parameter AVST_DATA_WIDTH NATURAL 8
set_parameter_property AVST_DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property AVST_DATA_WIDTH DISPLAY_NAME "Avalon Streaming data width"
set_parameter_property AVST_DATA_WIDTH TYPE NATURAL
set_parameter_property AVST_DATA_WIDTH UNITS Bits
set_parameter_property AVST_DATA_WIDTH ALLOWED_RANGES 1:1023
set_parameter_property AVST_DATA_WIDTH HDL_PARAMETER true
set dscpt \
"<html>
Set the data width of the Avalon Streaming interface. <br>
This parameter also sets <i>dataBitsPerSymbol</i> of the <b>rx</b> and <b>tx</b> interface. <br>
You have to set this paramter according to the length of a command of your sensor. <br>
Also referred to as <i>symbol</i> in the RTL code.  
<b>Default is 8.</b>
</html>"
set_parameter_property AVST_DATA_WIDTH LONG_DESCRIPTION $dscpt
set_parameter_property AVST_DATA_WIDTH DESCRIPTION $dscpt

add_parameter AVMM_DATA_WIDTH NATURAL 
set_parameter_property AVMM_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property AVMM_DATA_WIDTH DISPLAY_NAME "Avalon Memory-Mapped data width"
set_parameter_property AVMM_DATA_WIDTH TYPE NATURAL
set_parameter_property AVMM_DATA_WIDTH UNITS Bits
set_parameter_property AVMM_DATA_WIDTH ALLOWED_RANGES 1:1023
set_parameter_property AVMM_DATA_WIDTH HDL_PARAMETER true
set_parameter_property AVMM_DATA_WIDTH ENABLED false 
set dscpt \
"<html>
Set the data width of the Avalon Memory-Mapped interface. <br>
<b>Default is 32.</b>
</html>"
set_parameter_property AVMM_DATA_WIDTH LONG_DESCRIPTION $dscpt
set_parameter_property AVMM_DATA_WIDTH DESCRIPTION $dscpt

add_parameter AVST_CHANNEL_WIDTH NATURAL 
set_parameter_property AVST_CHANNEL_WIDTH DEFAULT_VALUE 3
set_parameter_property AVST_CHANNEL_WIDTH DISPLAY_NAME "Avalon Steaming channel width"
set_parameter_property AVST_CHANNEL_WIDTH TYPE NATURAL
set_parameter_property AVST_CHANNEL_WIDTH UNITS Bits
set_parameter_property AVST_CHANNEL_WIDTH ALLOWED_RANGES 0:7
set_parameter_property AVST_CHANNEL_WIDTH HDL_PARAMETER true
set dscpt \
"<html>
Set the channel width of the out-band signal of Avalon Streaming interface. <br>
<br>
<b>Note</b>: Must be larger than number of dq lines.
</html>"
set_parameter_property AVST_CHANNEL_WIDTH LONG_DESCRIPTION $dscpt
set_parameter_property AVST_CHANNEL_WIDTH DESCRIPTION $dscpt

add_parameter N_DQ_LINES NATURAL 
set_parameter_property N_DQ_LINES DEFAULT_VALUE 6
set_parameter_property N_DQ_LINES DISPLAY_NAME "Number of DQ lines"
set_parameter_property N_DQ_LINES TYPE NATURAL
set_parameter_property N_DQ_LINES UNITS None
set_parameter_property N_DQ_LINES ALLOWED_RANGES 1:255
set_parameter_property N_DQ_LINES HDL_PARAMETER true
set dscpt \
"<html>
Set the number of dq lines to connect to sensors. <br>
<b>Note:</b> this parameter has nothing to do with number of sensors on the line. <br>
It must match the setting in the <b>onewire master IP</b> <br>
To send, it used the memory-mapped settings. To receive, it used the streaming channel id.
</html>"
set_parameter_property N_DQ_LINES LONG_DESCRIPTION $dscpt
set_parameter_property N_DQ_LINES DESCRIPTION $dscpt


add_parameter SENSOR_TYPE STRING
set_parameter_property SENSOR_TYPE DEFAULT_VALUE DS18B20
set_parameter_property SENSOR_TYPE DISPLAY_NAME "Sensor type"
set_parameter_property SENSOR_TYPE ALLOWED_RANGES {"DS18B20"}
set_parameter_property SENSOR_TYPE TYPE STRING
set_parameter_property SENSOR_TYPE UNITS None
set_parameter_property SENSOR_TYPE HDL_PARAMETER true
set dscpt \
"<html>
Set the sensor type. This parameter affects the functional code sent. <br>
Only supported sensor type can be controlled, otherwise undefined behaviour could happen. 
</html>"
set_parameter_property SENSOR_TYPE LONG_DESCRIPTION $dscpt
set_parameter_property SENSOR_TYPE DESCRIPTION $dscpt

add_parameter DEBUG_LV NATURAL 
set_parameter_property DEBUG_LV DEFAULT_VALUE 0
set_parameter_property DEBUG_LV DISPLAY_NAME "Debug level"
set_parameter_property DEBUG_LV TYPE NATURAL
set_parameter_property DEBUG_LV UNITS None
set_parameter_property DEBUG_LV ALLOWED_RANGES {0 1 2}
set_parameter_property DEBUG_LV HDL_PARAMETER true
set dscpt \
"<html>
Select the debug level of the IP (affects generation).<br>
<ul>
	<li><b>0</b> : off <br> </li>
	<li><b>1</b> : on, synthesizble <br> </li>
	<li><b>2</b> : on, non-synthesizble, simulation-only <br> </li>
</ul>
</html>"
set_parameter_property DEBUG_LV LONG_DESCRIPTION $dscpt
set_parameter_property DEBUG_LV DESCRIPTION $dscpt


############################################
# display items
############################################
# --------------------------------------------------------------- 
add_display_item "" "IP Setting" GROUP ""
## ----
add_display_item "IP Setting" "System" GROUP ""
add_display_item "System" REF_CLOCK_RATE PARAMETER
## ----
add_display_item "IP Setting" "Ports" GROUP ""
add_display_item "Ports" AVST_DATA_WIDTH PARAMETER 
add_display_item "Ports" AVST_CHANNEL_WIDTH PARAMETER
add_display_item "Ports" AVMM_DATA_WIDTH PARAMETER 
## ----
add_display_item "IP Setting" "Version" GROUP ""
add_display_item "Version" DEBUG_LV PARAMETER 
# --------------------------------------------------------------- 
add_display_item "" "Sensor Setting" GROUP ""
## ----
add_display_item "Sensor Setting" SENSOR_TYPE PARAMETER
add_display_item "Sensor Setting" N_DQ_LINES PARAMETER



################################################
# connection point ctrl
################################################
add_interface ctrl avalon start
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl doStreamReads false
set_interface_property ctrl doStreamWrites false
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl maximumPendingWriteTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true
set_interface_property ctrl EXPORT_OF ""
set_interface_property ctrl PORT_NAME_MAP ""
set_interface_property ctrl CMSIS_SVD_VARIABLES ""
set_interface_property ctrl SVD_ADDRESS_GROUP ""

add_interface_port ctrl avm_ctrl_read read Output 1
add_interface_port ctrl avm_ctrl_readdata readdata Input avmm_data_width
add_interface_port ctrl avm_ctrl_write write Output 1
add_interface_port ctrl avm_ctrl_writedata writedata Output avmm_data_width
add_interface_port ctrl avm_ctrl_address address Output 4
add_interface_port ctrl avm_ctrl_waitrequest waitrequest Input 1


################################################
# connection point csr
################################################ 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_read read Input 1
add_interface_port csr avs_csr_readdata readdata Output avmm_data_width
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_writedata writedata Input avmm_data_width
add_interface_port csr avs_csr_address address Input 4
add_interface_port csr avs_csr_waitrequest waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


################################################ 
# connection point rx
################################################ 
add_interface rx avalon_streaming end
set_interface_property rx associatedClock clock
set_interface_property rx associatedReset reset
set_interface_property rx dataBitsPerSymbol 8
set_interface_property rx errorDescriptor ""
set_interface_property rx firstSymbolInHighOrderBits true
set_interface_property rx maxChannel 0
set_interface_property rx readyLatency 0
set_interface_property rx ENABLED true
set_interface_property rx EXPORT_OF ""
set_interface_property rx PORT_NAME_MAP ""
set_interface_property rx CMSIS_SVD_VARIABLES ""
set_interface_property rx SVD_ADDRESS_GROUP ""

add_interface_port rx asi_rx_data data Input avst_data_width
add_interface_port rx asi_rx_valid valid Input 1
add_interface_port rx asi_rx_ready ready Output 1
add_interface_port rx asi_rx_channel channel Input avst_channel_width


################################################ 
# connection point tx
################################################ 
add_interface tx avalon_streaming start
set_interface_property tx associatedClock clock
set_interface_property tx associatedReset reset
set_interface_property tx dataBitsPerSymbol 8
set_interface_property tx errorDescriptor ""
set_interface_property tx firstSymbolInHighOrderBits true
set_interface_property tx maxChannel 0
set_interface_property tx readyLatency 0
set_interface_property tx ENABLED true
set_interface_property tx EXPORT_OF ""
set_interface_property tx PORT_NAME_MAP ""
set_interface_property tx CMSIS_SVD_VARIABLES ""
set_interface_property tx SVD_ADDRESS_GROUP ""

add_interface_port tx aso_tx_data data Output avst_data_width
add_interface_port tx aso_tx_valid valid Output 1
add_interface_port tx aso_tx_ready ready Input 1
add_interface_port tx aso_tx_channel channel Output avst_channel_width


################################################ 
# connection point complete
################################################ 
add_interface complete interrupt start
set_interface_property complete associatedAddressablePoint ctrl
set_interface_property complete associatedClock clock
set_interface_property complete associatedReset reset
set_interface_property complete irqScheme INDIVIDUAL_REQUESTS
set_interface_property complete ENABLED true
set_interface_property complete EXPORT_OF ""
set_interface_property complete PORT_NAME_MAP ""
set_interface_property complete CMSIS_SVD_VARIABLES ""
set_interface_property complete SVD_ADDRESS_GROUP ""

add_interface_port complete inr_complete_irq irq Input 1


################################################ 
# connection point reset
################################################ 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_reset reset Input 1


################################################ 
# connection point clock
################################################ 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


proc myelaborate {} {
	# ----
	# set maxchannel	
	set_interface_property rx maxChannel [get_parameter_value "N_DQ_LINES"]
	set_interface_property tx maxChannel [get_parameter_value "N_DQ_LINES"]
	# ----
	# set clock rate
	set_interface_property clock clockRate [get_parameter_value "REF_CLOCK_RATE"]
	# ----
	# set beats per symbol
	set_interface_property rx dataBitsPerSymbol [get_parameter_value "AVST_DATA_WIDTH"]
	set_interface_property tx dataBitsPerSymbol [get_parameter_value "AVST_DATA_WIDTH"]
	
}
















