# TCL File Generated by Component Editor 18.1
# Wed Sep 18 17:12:41 CEST 2024
# MODIFIED


################################################ 
# onewire_master_controller "OneWire Master Controller" v1.0
# Yifeng Wang 2024.09.18.17:12:41
# Host transaction layer issues by process data from/into the onewire master IP.
################################################ 

################################################ 
# request TCL package from ACDS 16.1
################################################ 
package require -exact qsys 16.1

set IP_UID_DEFAULT_CONST 1331121475
set VERSION_MAJOR_DEFAULT_CONST 26
set VERSION_MINOR_DEFAULT_CONST 2
set VERSION_PATCH_DEFAULT_CONST 1
set BUILD_DEFAULT_CONST 428
set VERSION_DATE_DEFAULT_CONST 20260428
set VERSION_GIT_DEFAULT_CONST 0
set INSTANCE_ID_DEFAULT_CONST 0
set VERSION_STRING [format "%d.%d.%d.%04d" \
    $VERSION_MAJOR_DEFAULT_CONST \
    $VERSION_MINOR_DEFAULT_CONST \
    $VERSION_PATCH_DEFAULT_CONST \
    $BUILD_DEFAULT_CONST]

proc add_html_text {group_name item_name html_text} {
    add_display_item $group_name $item_name TEXT ""
    set_display_item_property $item_name DISPLAY_HINT html
    set_display_item_property $item_name TEXT $html_text
}


################################################ 
# module onewire_master_controller
################################################ 
set_module_property DESCRIPTION \
"<html>
Host transaction layer issues by process data from/into the onewire master IP. <br>
It wraps around the link layer by automatically perform functional commands on a specific 1-Wire device. <br>
<br>
Usage:

</html>"

set_module_property NAME onewire_master_controller
set_module_property VERSION $VERSION_STRING
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property ICON_PATH ../../../../../../firmware_builds/misc/logo/mu3e_logo.png
set_module_property DISPLAY_NAME "OneWire Master Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK myelaborate
set_module_property VALIDATION_CALLBACK myvalidate


################################################ 
# file sets
################################################ 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL onewire_master_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file onewire_master_controller.vhd VHDL PATH ../rtl/vhdl/onewire_master_controller/onewire_master_controller.vhd TOP_LEVEL_FILE
add_fileset_file pseudo_clock_down_convertor.vhd VHDL PATH ../rtl/common/pseudo_clock_down_convertor.vhd


################################################
# parameters
#################################################
add_parameter REF_CLOCK_RATE NATURAL 125000000
set_parameter_property REF_CLOCK_RATE DEFAULT_VALUE 125000000
set_parameter_property REF_CLOCK_RATE DISPLAY_NAME "Reference clock rate"
set_parameter_property REF_CLOCK_RATE TYPE NATURAL
set_parameter_property REF_CLOCK_RATE UNITS Hertz
set_parameter_property REF_CLOCK_RATE ALLOWED_RANGES 1_000_000:10_000_000_000
set_parameter_property REF_CLOCK_RATE HDL_PARAMETER true
set dscpt \
"<html>
Set the reference input clock rate. <br>
This IP has internal clock down-convertor for counting 1 us interval. <br>
The input must be greater <b>(&ge 1 MHz)</b> than the requirement of the timing parameter granularity, which is 1 us. <br>
<b> You only need to set this parameter according to your system bus clock rate. </b> 
</html>"
set_parameter_property REF_CLOCK_RATE LONG_DESCRIPTION $dscpt
set_parameter_property REF_CLOCK_RATE DESCRIPTION $dscpt

add_parameter AVST_DATA_WIDTH NATURAL 8
set_parameter_property AVST_DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property AVST_DATA_WIDTH DISPLAY_NAME "Avalon Streaming data width"
set_parameter_property AVST_DATA_WIDTH TYPE NATURAL
set_parameter_property AVST_DATA_WIDTH UNITS Bits
set_parameter_property AVST_DATA_WIDTH ALLOWED_RANGES 1:1023
set_parameter_property AVST_DATA_WIDTH HDL_PARAMETER true
set dscpt \
"<html>
Set the data width of the Avalon Streaming interface. <br>
This parameter also sets <i>dataBitsPerSymbol</i> of the <b>rx</b> and <b>tx</b> interface. <br>
You have to set this paramter according to the length of a command of your sensor. <br>
Also referred to as <i>symbol</i> in the RTL code.  
<b>Default is 8.</b>
</html>"
set_parameter_property AVST_DATA_WIDTH LONG_DESCRIPTION $dscpt
set_parameter_property AVST_DATA_WIDTH DESCRIPTION $dscpt

add_parameter AVMM_DATA_WIDTH NATURAL 
set_parameter_property AVMM_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property AVMM_DATA_WIDTH DISPLAY_NAME "Avalon Memory-Mapped data width"
set_parameter_property AVMM_DATA_WIDTH TYPE NATURAL
set_parameter_property AVMM_DATA_WIDTH UNITS Bits
set_parameter_property AVMM_DATA_WIDTH ALLOWED_RANGES 1:1023
set_parameter_property AVMM_DATA_WIDTH HDL_PARAMETER true
set_parameter_property AVMM_DATA_WIDTH ENABLED false 
set dscpt \
"<html>
Set the data width of the Avalon Memory-Mapped interface. <br>
<b>Default is 32.</b>
</html>"
set_parameter_property AVMM_DATA_WIDTH LONG_DESCRIPTION $dscpt
set_parameter_property AVMM_DATA_WIDTH DESCRIPTION $dscpt

add_parameter AVST_CHANNEL_WIDTH NATURAL 
set_parameter_property AVST_CHANNEL_WIDTH DEFAULT_VALUE 3
set_parameter_property AVST_CHANNEL_WIDTH DISPLAY_NAME "Avalon Steaming channel width"
set_parameter_property AVST_CHANNEL_WIDTH TYPE NATURAL
set_parameter_property AVST_CHANNEL_WIDTH UNITS Bits
set_parameter_property AVST_CHANNEL_WIDTH ALLOWED_RANGES 0:7
set_parameter_property AVST_CHANNEL_WIDTH HDL_PARAMETER true
set dscpt \
"<html>
Set the channel width of the out-band signal of Avalon Streaming interface. <br>
<br>
<b>Note</b>: Must be larger than number of dq lines.
</html>"
set_parameter_property AVST_CHANNEL_WIDTH LONG_DESCRIPTION $dscpt
set_parameter_property AVST_CHANNEL_WIDTH DESCRIPTION $dscpt

add_parameter N_DQ_LINES NATURAL 
set_parameter_property N_DQ_LINES DEFAULT_VALUE 6
set_parameter_property N_DQ_LINES DISPLAY_NAME "Number of DQ lines"
set_parameter_property N_DQ_LINES TYPE NATURAL
set_parameter_property N_DQ_LINES UNITS None
set_parameter_property N_DQ_LINES ALLOWED_RANGES 1:255
set_parameter_property N_DQ_LINES HDL_PARAMETER true
set dscpt \
"<html>
Set the number of dq lines to connect to sensors. <br>
<b>Note:</b> this parameter has nothing to do with number of sensors on the line. <br>
It must match the setting in the <b>onewire master IP</b> <br>
To send, it used the memory-mapped settings. To receive, it used the streaming channel id.
</html>"
set_parameter_property N_DQ_LINES LONG_DESCRIPTION $dscpt
set_parameter_property N_DQ_LINES DESCRIPTION $dscpt


add_parameter SENSOR_TYPE STRING
set_parameter_property SENSOR_TYPE DEFAULT_VALUE DS18B20
set_parameter_property SENSOR_TYPE DISPLAY_NAME "Sensor type"
set_parameter_property SENSOR_TYPE ALLOWED_RANGES {"DS18B20"}
set_parameter_property SENSOR_TYPE TYPE STRING
set_parameter_property SENSOR_TYPE UNITS None
set_parameter_property SENSOR_TYPE HDL_PARAMETER true
set dscpt \
"<html>
Set the sensor type. This parameter affects the functional code sent. <br>
Only supported sensor type can be controlled, otherwise undefined behaviour could happen. 
</html>"
set_parameter_property SENSOR_TYPE LONG_DESCRIPTION $dscpt
set_parameter_property SENSOR_TYPE DESCRIPTION $dscpt

add_parameter DEBUG_LV NATURAL 
set_parameter_property DEBUG_LV DEFAULT_VALUE 0
set_parameter_property DEBUG_LV DISPLAY_NAME "Debug level"
set_parameter_property DEBUG_LV TYPE NATURAL
set_parameter_property DEBUG_LV UNITS None
set_parameter_property DEBUG_LV ALLOWED_RANGES {0 1 2}
set_parameter_property DEBUG_LV HDL_PARAMETER true
set dscpt \
"<html>
Select the debug level of the IP (affects generation).<br>
<ul>
	<li><b>0</b> : off <br> </li>
	<li><b>1</b> : on, synthesizble <br> </li>
	<li><b>2</b> : on, non-synthesizble, simulation-only <br> </li>
</ul>
</html>"
set_parameter_property DEBUG_LV LONG_DESCRIPTION $dscpt
set_parameter_property DEBUG_LV DESCRIPTION $dscpt

add_parameter IP_UID NATURAL $IP_UID_DEFAULT_CONST
set_parameter_property IP_UID DEFAULT_VALUE $IP_UID_DEFAULT_CONST
set_parameter_property IP_UID DISPLAY_NAME "UID"
set_parameter_property IP_UID TYPE NATURAL
set_parameter_property IP_UID UNITS None
set_parameter_property IP_UID ALLOWED_RANGES 0:2147483647
set_parameter_property IP_UID HDL_PARAMETER true
set_parameter_property IP_UID DISPLAY_HINT hexadecimal
set_parameter_property IP_UID DESCRIPTION {Software-visible IP identifier. Default corresponds to ASCII "OWMC".}

add_parameter VERSION_MAJOR NATURAL $VERSION_MAJOR_DEFAULT_CONST
set_parameter_property VERSION_MAJOR DEFAULT_VALUE $VERSION_MAJOR_DEFAULT_CONST
set_parameter_property VERSION_MAJOR DISPLAY_NAME "Version Major"
set_parameter_property VERSION_MAJOR TYPE NATURAL
set_parameter_property VERSION_MAJOR UNITS None
set_parameter_property VERSION_MAJOR ALLOWED_RANGES 0:255
set_parameter_property VERSION_MAJOR HDL_PARAMETER true
set_parameter_property VERSION_MAJOR ENABLED false

add_parameter VERSION_MINOR NATURAL $VERSION_MINOR_DEFAULT_CONST
set_parameter_property VERSION_MINOR DEFAULT_VALUE $VERSION_MINOR_DEFAULT_CONST
set_parameter_property VERSION_MINOR DISPLAY_NAME "Version Minor"
set_parameter_property VERSION_MINOR TYPE NATURAL
set_parameter_property VERSION_MINOR UNITS None
set_parameter_property VERSION_MINOR ALLOWED_RANGES 0:255
set_parameter_property VERSION_MINOR HDL_PARAMETER true
set_parameter_property VERSION_MINOR ENABLED false

add_parameter VERSION_PATCH NATURAL $VERSION_PATCH_DEFAULT_CONST
set_parameter_property VERSION_PATCH DEFAULT_VALUE $VERSION_PATCH_DEFAULT_CONST
set_parameter_property VERSION_PATCH DISPLAY_NAME "Version Patch"
set_parameter_property VERSION_PATCH TYPE NATURAL
set_parameter_property VERSION_PATCH UNITS None
set_parameter_property VERSION_PATCH ALLOWED_RANGES 0:15
set_parameter_property VERSION_PATCH HDL_PARAMETER true
set_parameter_property VERSION_PATCH ENABLED false

add_parameter BUILD NATURAL $BUILD_DEFAULT_CONST
set_parameter_property BUILD DEFAULT_VALUE $BUILD_DEFAULT_CONST
set_parameter_property BUILD DISPLAY_NAME "Build Stamp"
set_parameter_property BUILD TYPE NATURAL
set_parameter_property BUILD UNITS None
set_parameter_property BUILD ALLOWED_RANGES 0:4095
set_parameter_property BUILD HDL_PARAMETER true
set_parameter_property BUILD ENABLED false

add_parameter VERSION_DATE NATURAL $VERSION_DATE_DEFAULT_CONST
set_parameter_property VERSION_DATE DEFAULT_VALUE $VERSION_DATE_DEFAULT_CONST
set_parameter_property VERSION_DATE DISPLAY_NAME "Version Date"
set_parameter_property VERSION_DATE TYPE NATURAL
set_parameter_property VERSION_DATE UNITS None
set_parameter_property VERSION_DATE ALLOWED_RANGES 20200101:20991231
set_parameter_property VERSION_DATE HDL_PARAMETER true
set_parameter_property VERSION_DATE ENABLED false

add_parameter VERSION_GIT NATURAL $VERSION_GIT_DEFAULT_CONST
set_parameter_property VERSION_GIT DEFAULT_VALUE $VERSION_GIT_DEFAULT_CONST
set_parameter_property VERSION_GIT DISPLAY_NAME "Version Git"
set_parameter_property VERSION_GIT TYPE NATURAL
set_parameter_property VERSION_GIT UNITS None
set_parameter_property VERSION_GIT ALLOWED_RANGES 0:2147483647
set_parameter_property VERSION_GIT HDL_PARAMETER true
set_parameter_property VERSION_GIT ENABLED false
set_parameter_property VERSION_GIT DISPLAY_HINT hexadecimal

add_parameter INSTANCE_ID NATURAL $INSTANCE_ID_DEFAULT_CONST
set_parameter_property INSTANCE_ID DEFAULT_VALUE $INSTANCE_ID_DEFAULT_CONST
set_parameter_property INSTANCE_ID DISPLAY_NAME "Instance ID"
set_parameter_property INSTANCE_ID TYPE NATURAL
set_parameter_property INSTANCE_ID UNITS None
set_parameter_property INSTANCE_ID ALLOWED_RANGES 0:2147483647
set_parameter_property INSTANCE_ID HDL_PARAMETER true
set_parameter_property INSTANCE_ID DESCRIPTION {Integration-time instance identifier exposed through META page 3.}


############################################
# display items
############################################
add_display_item "" "Configuration" GROUP ""
add_display_item "Configuration" "Sensor Loop" GROUP ""
add_display_item "Sensor Loop" REF_CLOCK_RATE PARAMETER
add_display_item "Sensor Loop" SENSOR_TYPE PARAMETER
add_display_item "Sensor Loop" N_DQ_LINES PARAMETER
add_display_item "Configuration" "Avalon Interfaces" GROUP ""
add_display_item "Avalon Interfaces" AVST_DATA_WIDTH PARAMETER
add_display_item "Avalon Interfaces" AVST_CHANNEL_WIDTH PARAMETER
add_display_item "Avalon Interfaces" AVMM_DATA_WIDTH PARAMETER
add_display_item "Configuration" "Debug" GROUP ""
add_display_item "Debug" DEBUG_LV PARAMETER

add_display_item "" "Identity" GROUP ""
add_display_item "Identity" "Versioning" GROUP ""
add_html_text "Versioning" "Delivered Profile" "<html><b>OneWire Master Controller</b><br>Version $VERSION_STRING<br>Date $VERSION_DATE_DEFAULT_CONST<br>FEB profile: six independent DS18B20 DQ lines, one sensor per line.<br><br><b>Runtime visibility</b><br>Software can blind-scan the CSR window through <b>UID</b> at word <b>0</b> and the <b>META</b> mux at word <b>1</b>.</html>"
add_html_text "Versioning" "Common Header" "<html><b>Common identity header</b><br>Word <b>0</b> is <b>UID</b>.<br>Word <b>1</b> is <b>META</b>: write <b>0</b>=VERSION, <b>1</b>=DATE, <b>2</b>=GIT, <b>3</b>=INSTANCE_ID.<br><br><b>VERSION encoding</b><br>VERSION bit 31..24 = MAJOR, bit 23..16 = MINOR, bit 15..12 = PATCH, bit 11..0 = BUILD.</html>"
add_display_item "Versioning" IP_UID PARAMETER
add_display_item "Versioning" VERSION_MAJOR PARAMETER
add_display_item "Versioning" VERSION_MINOR PARAMETER
add_display_item "Versioning" VERSION_PATCH PARAMETER
add_display_item "Versioning" BUILD PARAMETER
add_display_item "Versioning" VERSION_DATE PARAMETER
add_display_item "Versioning" VERSION_GIT PARAMETER
add_display_item "Versioning" INSTANCE_ID PARAMETER

add_display_item "" "Interfaces" GROUP ""
add_html_text "Interfaces" "Interface Summary" "<html><table border=\"1\" cellpadding=\"3\"><tr><th>Interface</th><th>Role</th><th>Description</th></tr><tr><td>ctrl</td><td>Avalon-MM master</td><td>Issues commands to the onewire_master link layer.</td></tr><tr><td>csr</td><td>Avalon-MM slave</td><td>Host control, status, and temperature readback aperture.</td></tr><tr><td>tx</td><td>Avalon-ST source</td><td>Command bytes sent to the link layer.</td></tr><tr><td>rx</td><td>Avalon-ST sink</td><td>Scratchpad bytes returned by the link layer.</td></tr><tr><td>complete</td><td>Interrupt receiver</td><td>Transaction completion IRQ from the link layer.</td></tr></table></html>"

add_display_item "" "Register Map" GROUP ""
add_html_text "Register Map" "CSR Words" "<html><table border=\"1\" cellpadding=\"3\"><tr><th>Word</th><th>Name</th><th>Access</th><th>Description</th></tr><tr><td>0</td><td>UID</td><td>RO</td><td>Software-visible IP identifier. Default is ASCII <b>OWMC</b>.</td></tr><tr><td>1</td><td>META</td><td>RW/RO</td><td>Read-multiplexed metadata word. Write <b>0</b>=VERSION, <b>1</b>=DATE, <b>2</b>=GIT, <b>3</b>=INSTANCE_ID. VERSION is packed as MAJOR bits 31..24, MINOR bits 23..16, PATCH bits 15..12, BUILD bits 11..0.</td></tr><tr><td>2</td><td>SCRATCH</td><td>RW</td><td>Host scratchpad/readback word for software liveness tests.</td></tr><tr><td>3</td><td>CAPABILITY</td><td>RO</td><td>bits 15:0 n_dq_lines, bits 31:16 n_sensors reserved zero until the Read-ROM probe is implemented.</td></tr><tr><td>4</td><td>STATUS</td><td>RW</td><td>bits 15:0 sel_line, bit 16 processor_go, bit 24 crc_err, bit 25 init_err, bit 26 sample_valid. Future Read-ROM status bits must live above bit 26.</td></tr><tr><td>5..10</td><td>SENSORn_TEMP_F32</td><td>RO</td><td>IEEE-754 float32 temperature for DQ line n. Reads zero until sample_valid is set for that line.</td></tr></table></html>"



################################################
# connection point ctrl
################################################
add_interface ctrl avalon start
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl doStreamReads false
set_interface_property ctrl doStreamWrites false
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl maximumPendingWriteTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true
set_interface_property ctrl EXPORT_OF ""
set_interface_property ctrl PORT_NAME_MAP ""
set_interface_property ctrl CMSIS_SVD_VARIABLES ""
set_interface_property ctrl SVD_ADDRESS_GROUP ""

add_interface_port ctrl avm_ctrl_read read Output 1
add_interface_port ctrl avm_ctrl_readdata readdata Input avmm_data_width
add_interface_port ctrl avm_ctrl_write write Output 1
add_interface_port ctrl avm_ctrl_writedata writedata Output avmm_data_width
add_interface_port ctrl avm_ctrl_address address Output 4
add_interface_port ctrl avm_ctrl_waitrequest waitrequest Input 1


################################################
# connection point csr
################################################ 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 1
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_read read Input 1
add_interface_port csr avs_csr_readdata readdata Output avmm_data_width
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_writedata writedata Input avmm_data_width
add_interface_port csr avs_csr_address address Input 4
add_interface_port csr avs_csr_waitrequest waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


################################################ 
# connection point rx
################################################ 
add_interface rx avalon_streaming end
set_interface_property rx associatedClock clock
set_interface_property rx associatedReset reset
set_interface_property rx dataBitsPerSymbol 8
set_interface_property rx errorDescriptor ""
set_interface_property rx firstSymbolInHighOrderBits true
set_interface_property rx maxChannel 0
set_interface_property rx readyLatency 0
set_interface_property rx ENABLED true
set_interface_property rx EXPORT_OF ""
set_interface_property rx PORT_NAME_MAP ""
set_interface_property rx CMSIS_SVD_VARIABLES ""
set_interface_property rx SVD_ADDRESS_GROUP ""

add_interface_port rx asi_rx_data data Input avst_data_width
add_interface_port rx asi_rx_valid valid Input 1
add_interface_port rx asi_rx_ready ready Output 1
add_interface_port rx asi_rx_channel channel Input avst_channel_width


################################################ 
# connection point tx
################################################ 
add_interface tx avalon_streaming start
set_interface_property tx associatedClock clock
set_interface_property tx associatedReset reset
set_interface_property tx dataBitsPerSymbol 8
set_interface_property tx errorDescriptor ""
set_interface_property tx firstSymbolInHighOrderBits true
set_interface_property tx maxChannel 0
set_interface_property tx readyLatency 0
set_interface_property tx ENABLED true
set_interface_property tx EXPORT_OF ""
set_interface_property tx PORT_NAME_MAP ""
set_interface_property tx CMSIS_SVD_VARIABLES ""
set_interface_property tx SVD_ADDRESS_GROUP ""

add_interface_port tx aso_tx_data data Output avst_data_width
add_interface_port tx aso_tx_valid valid Output 1
add_interface_port tx aso_tx_ready ready Input 1
add_interface_port tx aso_tx_channel channel Output avst_channel_width


################################################ 
# connection point complete
################################################ 
add_interface complete interrupt start
set_interface_property complete associatedAddressablePoint ctrl
set_interface_property complete associatedClock clock
set_interface_property complete associatedReset reset
set_interface_property complete irqScheme INDIVIDUAL_REQUESTS
set_interface_property complete ENABLED true
set_interface_property complete EXPORT_OF ""
set_interface_property complete PORT_NAME_MAP ""
set_interface_property complete CMSIS_SVD_VARIABLES ""
set_interface_property complete SVD_ADDRESS_GROUP ""

add_interface_port complete inr_complete_irq irq Input 1


################################################ 
# connection point reset
################################################ 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_reset reset Input 1


################################################ 
# connection point clock
################################################ 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


proc myelaborate {} {
	# ----
	# set maxchannel	
	set_interface_property rx maxChannel [get_parameter_value "N_DQ_LINES"]
	set_interface_property tx maxChannel [get_parameter_value "N_DQ_LINES"]
	# ----
	# set clock rate
	set_interface_property clock clockRate [get_parameter_value "REF_CLOCK_RATE"]
	# ----
	# set beats per symbol
	set_interface_property rx dataBitsPerSymbol [get_parameter_value "AVST_DATA_WIDTH"]
	set_interface_property tx dataBitsPerSymbol [get_parameter_value "AVST_DATA_WIDTH"]
	return -code ok
}

proc myvalidate {} {
	if {[get_parameter_value "N_DQ_LINES"] < 1} {
		send_message error "N_DQ_LINES must be at least one."
	}
	if {[get_parameter_value "REF_CLOCK_RATE"] < 1000000} {
		send_message error "REF_CLOCK_RATE must be at least 1 MHz."
	}
	return -code ok
}


